# vim: ft=yaml ts=2:
---

- name: set OS specific variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- debug: var=apache
  tags:
    - never
    - debug

- debug: var=php
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - ansible_os_family in ["RedHat"]
      - php.package is defined

- name: assertions
  when: php_scl_name is defined
  assert:
    that:
      - apache.scl.prefix is defined

- name: php is installed
  package:
    name: "{{ php.package }}"
    state: present
  notify: restart apache

- debug: msg="/etc/opt/{{ apache.scl.prefix }}/conf.modules.d/15-{{ php_scl_name }}-php.conf"
  tags:
    - never
    - debug

- name: mod_php is enabled
  template:
    src: "{{ ansible_os_family }}-{{ php_scl_name|regex_replace('.+([0-9]{1}).+','\\1') }}.conf.modules.conf.j2"
    dest: /etc/opt/{{ apache.scl.prefix }}/{{ apache.scl.name }}/conf.modules.d/15-{{ php_scl_name }}-php.conf
    backup: true
  notify: restart apache

- name: symlink into /etc/profile.d
  when: php.scl.enabled == true
  file:
    src: /opt/{{ php.scl.prefix }}/{{ php_scl_name }}/enable
    dest: /etc/profile.d/{{ php_scl_name }}.sh
    state: link

- name: symlink into /etc/profile.d
  when: php.scl.enabled == false
  file:
    path: /etc/profile.d/{{ php_scl_name }}.sh
    state: absent
