---

- name: php-fpm is installed
  package:
    name: "{{ php_fpm.package }}"
    state: installed

- name: php-fpm service is running
  service:
    name: "{{ php_fpm.package }}"
    state: started
