---

- name: user for php-fpm pool {{ php_fpm_pool.pool }} exists
  user:
    name: "{{ login }}"
    uid: "{{ uid }}"
    group: "{{ group }}"
    shell: /sbin/nologin
    home: "{{ homedir }}"

- name: php-fpm pool {{ php_fpm_pool.pool }} is configured
  template:
    src: php-fpm.d.j2
    dest: "{{ php_fpm.etcdir }}/php-fpm.d/{{ pool }}.conf"
  notify: reload php-fpm
